# Generated by Django 5.2 on 2025-04-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="goals",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.TextField(blank=True),
        ),
    ]
