# Generated by Django 5.2 on 2025-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_goals_profile_industry_profile_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="seeking_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="startup_stage",
            field=models.CharField(
                choices=[
                    ("ideation", "Ideation"),
                    ("early_stage", "Early Stage"),
                    ("growth", "Growth"),
                    ("scaling", "Scaling"),
                    ("established", "Established"),
                ],
                default="ideation",
                max_length=50,
            ),
        ),
    ]
