# Generated by Django 5.2 on 2025-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_experience_years_profile_seeking_roles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="startup_stage",
            field=models.CharField(
                choices=[
                    ("pre_idea", "Pre-Idea Exploration"),
                    ("ideation", "Ideation/Concept"),
                    ("prototype", "Prototype Development"),
                    ("mvp", "MVP"),
                    ("pre_seed", "Pre-Seed/Early Traction"),
                    ("seed", "Seed/Traction"),
                    ("scaling", "Scaling/Growth"),
                    ("established", "Established/Post Series-A"),
                    ("expansion", "Expansion/Post Series-B"),
                    ("pivot", "Pivot"),
                ],
                default="pre_idea",
                max_length=50,
            ),
        ),
    ]
