# Generated by Django 5.2 on 2025-04-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_startup_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
