# Generated by Django 5.2 on 2025-04-26 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("tagline", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("industry", models.CharField(max_length=100)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("pre_idea", "Pre-Idea Exploration"),
                            ("ideation", "Ideation/Concept"),
                            ("prototype", "Prototype Development"),
                            ("mvp", "MVP"),
                            ("pre_seed", "Pre-Seed/Early Traction"),
                            ("seed", "Seed/Traction"),
                            ("scaling", "Scaling/Growth"),
                            ("established", "Established/Post Series-A"),
                            ("expansion", "Expansion/Post Series-B"),
                            ("pivot", "Pivot"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "startup_type",
                    models.CharField(
                        choices=[
                            ("B2B", "Business to Business"),
                            ("B2C", "Business to Consumer"),
                            ("B2B2C", "Business to Business to Consumer"),
                            ("C2C", "Consumer to Consumer"),
                            ("B2G", "Business to Government"),
                            ("G2C", "Government to Consumer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("business_model", models.JSONField(default=list)),
                ("team_size", models.IntegerField(default=1)),
                ("website", models.URLField(blank=True)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
