# Generated by Django 5.2 on 2025-04-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="equity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="project",
            name="funding",
            field=models.CharField(
                choices=[
                    ("self_funded", "Self-Funded"),
                    ("loan", "Loan"),
                    ("investment", "Invested"),
                    ("sponsored", "Sponsored"),
                    ("Others", "Others"),
                ],
                default="self_funded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="market_traction",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="project",
            name="startup_type",
            field=models.CharField(
                choices=[
                    ("B2B", "Business to Business"),
                    ("B2C", "Business to Consumer"),
                    ("B2B2C", "Business to Business to Consumer"),
                    ("C2C", "Consumer to Consumer"),
                    ("B2G", "Business to Government"),
                    ("G2C", "Government to Consumer"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
